//! TypeScript binding generation for the Tauri GUI shell.

use std::{fs, path::Path};

use tessera_client::{
    ClientApproval, ClientApprovalStatus, ClientArtifact, ClientContextBudgetSummary,
    ClientContextHandle, ClientContextPlacement, ClientContextSourceKind, ClientIntent,
    ClientMemoryProposal, ClientMemoryProposalStatus, ClientMessage, ClientMessageRole,
    ClientProjection, ClientSnapshot, ClientStatus, ClientTask, ClientTelemetrySummary,
};
use tessera_gui_bridge::{GuiCommandOutcome, GuiEvent, GuiProfile, GuiRuntimeMode, GuiShellState};
use tessera_protocol::{
    ApprovalId, ArtifactId, ArtifactKind, ContextId, EventId, ItemId, MemoryProposalId, TaskId,
    TaskKind, TaskStatus, ThreadId, Timestamp, ToolCallId, ToolId, TraceRecord, TurnId,
};
use ts_rs::{Config, TS};

const HEADER: &str = "\
// This file is generated by `cargo run -p tessera-gui-bindings -- apps/gui-tauri/src/generated/bindings.ts`.
// Do not edit this file manually.

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

";

pub fn generate_bindings() -> String {
    let cfg = Config::new().with_large_int("number");
    let mut output = String::from(HEADER);

    push_decl::<ArtifactId>(&mut output, &cfg);
    push_decl::<ArtifactKind>(&mut output, &cfg);
    push_decl::<ApprovalId>(&mut output, &cfg);
    push_decl::<ClientApproval>(&mut output, &cfg);
    push_decl::<ClientApprovalStatus>(&mut output, &cfg);
    push_decl::<ClientArtifact>(&mut output, &cfg);
    push_decl::<ClientContextBudgetSummary>(&mut output, &cfg);
    push_decl::<ClientContextHandle>(&mut output, &cfg);
    push_decl::<ClientContextPlacement>(&mut output, &cfg);
    push_decl::<ClientContextSourceKind>(&mut output, &cfg);
    push_decl::<ClientIntent>(&mut output, &cfg);
    push_decl::<ClientMemoryProposal>(&mut output, &cfg);
    push_decl::<ClientMemoryProposalStatus>(&mut output, &cfg);
    push_decl::<ClientMessage>(&mut output, &cfg);
    push_decl::<ClientMessageRole>(&mut output, &cfg);
    push_decl::<ClientProjection>(&mut output, &cfg);
    push_decl::<ClientSnapshot>(&mut output, &cfg);
    push_decl::<ClientStatus>(&mut output, &cfg);
    push_decl::<ClientTask>(&mut output, &cfg);
    push_decl::<ClientTelemetrySummary>(&mut output, &cfg);
    push_decl::<ContextId>(&mut output, &cfg);
    push_decl::<EventId>(&mut output, &cfg);
    push_decl::<GuiCommandOutcome>(&mut output, &cfg);
    push_decl::<GuiEvent>(&mut output, &cfg);
    push_decl::<GuiProfile>(&mut output, &cfg);
    push_decl::<GuiRuntimeMode>(&mut output, &cfg);
    push_decl::<GuiShellState>(&mut output, &cfg);
    push_decl::<ItemId>(&mut output, &cfg);
    push_decl::<MemoryProposalId>(&mut output, &cfg);
    push_decl::<TaskId>(&mut output, &cfg);
    push_decl::<TaskKind>(&mut output, &cfg);
    push_decl::<TaskStatus>(&mut output, &cfg);
    push_decl::<ThreadId>(&mut output, &cfg);
    push_decl::<Timestamp>(&mut output, &cfg);
    push_decl::<ToolCallId>(&mut output, &cfg);
    push_decl::<ToolId>(&mut output, &cfg);
    push_decl::<TraceRecord>(&mut output, &cfg);
    push_decl::<TurnId>(&mut output, &cfg);

    output.truncate(output.trim_end_matches('\n').len());
    output.push('\n');

    output
}

pub fn write_bindings(path: impl AsRef<Path>) -> std::io::Result<()> {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, generate_bindings())
}

fn push_decl<T>(output: &mut String, cfg: &Config)
where
    T: TS,
{
    output.push_str(&export_decl(T::decl(cfg)));
    output.push_str("\n\n");
}

fn export_decl(decl: String) -> String {
    decl.strip_prefix("type ")
        .map(|rest| format!("export type {rest}"))
        .unwrap_or(decl)
}
