//! TypeScript binding generation for the Tauri GUI shell.

use std::{fs, path::Path};

use tessera_client::{
    ClientAgentHandoff, ClientApproval, ClientApprovalStatus, ClientArtifact, ClientCodingWorkflow,
    ClientContextBudgetSummary, ClientContextHandle, ClientContextPlacement,
    ClientContextSourceKind, ClientIntent, ClientMemoryProposal, ClientMemoryProposalStatus,
    ClientMessage, ClientMessageRole, ClientProjection, ClientReviewerGate,
    ClientReviewerGateStatus, ClientSnapshot, ClientStatus, ClientSubagentApprovalForwarding,
    ClientSubagentApprovalForwardingStatus, ClientSubagentCancellation,
    ClientSubagentCancellationCascade, ClientSubagentInactiveParentAction,
    ClientSubagentInactivePolicy, ClientSubagentRuntimeDecision, ClientSubagentRuntimeDecisionKind,
    ClientSubagentSession, ClientSubagentSessionStatus, ClientSubagentTranscriptArtifact,
    ClientSubagentTranscriptArtifactLifecycle, ClientSubagentTranscriptArtifactStatus, ClientTask,
    ClientTelemetrySummary, ClientWorktreeLifecycle,
};
use tessera_gui_bridge::{GuiCommandOutcome, GuiEvent, GuiProfile, GuiRuntimeMode, GuiShellState};
use tessera_protocol::{
    AgentHandoffId, AgentHandoffMetrics, AgentHandoffStatus, AgentHandoffSummary, AgentProfileId,
    ApplyPatchDryRunOperationKind, ApplyPatchDryRunOperationSummary, ApplyPatchExecutionBlocker,
    ApplyPatchExecutionId, ApplyPatchExecutionRecord, ApplyPatchExecutionStatus,
    ApplyPatchPreflightBlocker, ApplyPatchPreflightId, ApplyPatchPreflightRecord,
    ApplyPatchPreflightStatus, ApprovalId, ArtifactBodyRecord, ArtifactBodyRedactionStatus,
    ArtifactId, ArtifactKind, ClientInstanceId, CodingWorkflowEvidenceRedactionStatus,
    CodingWorkflowId, ContextId, CostEstimate, EventId, EventRange, HandoffEvidenceKind,
    HandoffEvidenceRef, ItemId, MemoryProposalId, MutationMode, MutationRequestId,
    MutationRequestOperationKind, MutationRequestProposal, MutationRequestStatus,
    PatchApplicationOutcome, PatchApplicationRecord, PatchProposal, PatchProposalId, RestorePlanId,
    RestorePlanRecord, ReviewBundle, ReviewBundleId, ReviewerDecisionKind, ReviewerGateDecision,
    ReviewerGateId, ReviewerGateRequest, RuntimeApiAuthMode, RuntimeApiAuthPolicy,
    RuntimeApiBindConfig, RuntimeApiBindKind, RuntimeApiCommand, RuntimeApiCommandAck,
    RuntimeApiCommandEnvelope, RuntimeApiCommandStatus, RuntimeApiEventStreamRequest,
    RuntimeApiQueueOverflow, RuntimeApiQueuePolicy, RuntimeApiServerConfig, RuntimeInstanceId,
    SnapshotId, SubagentApprovalForwarding, SubagentApprovalForwardingRecord,
    SubagentApprovalForwardingStatus, SubagentCancellationCascade, SubagentCancellationRecord,
    SubagentInactiveParentAction, SubagentInactivePolicy, SubagentInactivePolicyRecord,
    SubagentRuntimeDecision, SubagentRuntimeDecisionKind, SubagentSessionCaps,
    SubagentSessionDescriptor, SubagentSessionId, SubagentSessionStatus,
    SubagentTranscriptArtifactLifecycleRecord, SubagentTranscriptArtifactRecord,
    SubagentTranscriptArtifactStatus, TaskId, TaskKind, TaskOwnerKind, TaskOwnerStatus,
    TaskOwnershipId, TaskReattachMode, TaskStatus, TestPlanId, TestPlanRecord, TestRunId,
    TestRunRecord, TestRunStatus, ThreadId, Timestamp, ToolCallId, ToolId, TraceRecord, TurnId,
    WorkspaceCheckpointLifecycleRecord, WorkspaceCheckpointLifecycleStatus, WorkspaceMutationScope,
};
use ts_rs::{Config, TS};

const HEADER: &str = "\
// This file is generated by `cargo run -p tessera-gui-bindings -- apps/gui-tauri/src/generated/bindings.ts`.
// Do not edit this file manually.

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

";

const TRACE_EVENT_KIND_DECL: &str = "\
export type TraceEventKind = \"thread_created\" | \"turn_started\" | \"user_message_recorded\" | \"provider_request_started\" | \"assistant_message_started\" | \"assistant_delta\" | \"assistant_reasoning_delta\" | \"assistant_message_completed\" | \"usage_reported\" | \"provider_capability_reported\" | \"route_decision_recorded\" | \"provider_request_completed\" | \"turn_completed\" | \"task_created\" | \"task_started\" | \"task_completed\" | \"task_failed\" | \"task_cancelled\" | \"task_pause_checkpoint_created\" | \"task_paused\" | \"task_resumed\" | \"runtime_instance_started\" | \"task_owner_attached\" | \"task_owner_heartbeat\" | \"task_owner_detached\" | \"task_owner_lost\" | \"task_reattach_recorded\" | \"agent_run_started\" | \"agent_step_started\" | \"agent_step_completed\" | \"agent_run_completed\" | \"agent_handoff_recorded\" | \"reviewer_gate_requested\" | \"reviewer_gate_resolved\" | \"coding_workflow_started\" | \"workspace_mutation_scope_recorded\" | \"mutation_request_proposal_recorded\" | \"apply_patch_preflight_recorded\" | \"apply_patch_execution_recorded\" | \"patch_proposal_recorded\" | \"patch_application_recorded\" | \"test_plan_recorded\" | \"test_run_recorded\" | \"review_bundle_recorded\" | \"restore_plan_recorded\" | \"subagent_session_planned\" | \"subagent_session_started\" | \"subagent_session_waiting_for_approval\" | \"subagent_session_inactive\" | \"subagent_session_completed\" | \"subagent_runtime_decision_recorded\" | \"subagent_transcript_artifact_recorded\" | \"subagent_transcript_artifact_lifecycle_recorded\" | \"subagent_approval_forwarding_recorded\" | \"subagent_inactive_policy_recorded\" | \"subagent_cancellation_recorded\" | \"no_progress_loop_detected\" | \"diagnostics_reported\" | \"memory_write_proposed\" | \"memory_write_applied\" | \"memory_write_rejected\" | \"artifact_created\" | \"artifact_body_recorded\" | \"snapshot_created\" | \"snapshot_lifecycle_recorded\" | \"tool_call_requested\" | \"tool_policy_decision_recorded\" | \"sandbox_decision_recorded\" | \"os_sandbox_profile_selected\" | \"tool_dispatch_started\" | \"tool_dispatch_completed\" | \"tool_result\" | \"tool_repair_reported\" | \"tool_call_approved\" | \"tool_call_denied\" | \"error\" | \"done\";
";

pub fn generate_bindings() -> String {
    let cfg = Config::new().with_large_int("number");
    let mut output = String::from(HEADER);

    push_decl::<AgentHandoffId>(&mut output, &cfg);
    push_decl::<AgentHandoffMetrics>(&mut output, &cfg);
    push_decl::<AgentHandoffStatus>(&mut output, &cfg);
    push_decl::<AgentHandoffSummary>(&mut output, &cfg);
    push_decl::<AgentProfileId>(&mut output, &cfg);
    push_decl::<ArtifactBodyRecord>(&mut output, &cfg);
    push_decl::<ArtifactBodyRedactionStatus>(&mut output, &cfg);
    push_decl::<ArtifactId>(&mut output, &cfg);
    push_decl::<ArtifactKind>(&mut output, &cfg);
    push_decl::<ApprovalId>(&mut output, &cfg);
    push_decl::<ClientAgentHandoff>(&mut output, &cfg);
    push_decl::<ClientApproval>(&mut output, &cfg);
    push_decl::<ClientApprovalStatus>(&mut output, &cfg);
    push_decl::<ClientArtifact>(&mut output, &cfg);
    push_decl::<ClientCodingWorkflow>(&mut output, &cfg);
    push_decl::<ClientInstanceId>(&mut output, &cfg);
    push_decl::<CodingWorkflowEvidenceRedactionStatus>(&mut output, &cfg);
    push_decl::<CodingWorkflowId>(&mut output, &cfg);
    push_decl::<ClientContextBudgetSummary>(&mut output, &cfg);
    push_decl::<ClientContextHandle>(&mut output, &cfg);
    push_decl::<ClientContextPlacement>(&mut output, &cfg);
    push_decl::<ClientContextSourceKind>(&mut output, &cfg);
    push_decl::<ClientIntent>(&mut output, &cfg);
    push_decl::<ClientMemoryProposal>(&mut output, &cfg);
    push_decl::<ClientMemoryProposalStatus>(&mut output, &cfg);
    push_decl::<ClientMessage>(&mut output, &cfg);
    push_decl::<ClientMessageRole>(&mut output, &cfg);
    push_decl::<ClientProjection>(&mut output, &cfg);
    push_decl::<ClientReviewerGate>(&mut output, &cfg);
    push_decl::<ClientReviewerGateStatus>(&mut output, &cfg);
    push_decl::<ClientSnapshot>(&mut output, &cfg);
    push_decl::<ClientStatus>(&mut output, &cfg);
    push_decl::<ClientSubagentApprovalForwarding>(&mut output, &cfg);
    push_decl::<ClientSubagentApprovalForwardingStatus>(&mut output, &cfg);
    push_decl::<ClientSubagentCancellation>(&mut output, &cfg);
    push_decl::<ClientSubagentCancellationCascade>(&mut output, &cfg);
    push_decl::<ClientSubagentInactiveParentAction>(&mut output, &cfg);
    push_decl::<ClientSubagentInactivePolicy>(&mut output, &cfg);
    push_decl::<ClientSubagentRuntimeDecision>(&mut output, &cfg);
    push_decl::<ClientSubagentRuntimeDecisionKind>(&mut output, &cfg);
    push_decl::<ClientSubagentSession>(&mut output, &cfg);
    push_decl::<ClientSubagentSessionStatus>(&mut output, &cfg);
    push_decl::<ClientSubagentTranscriptArtifact>(&mut output, &cfg);
    push_decl::<ClientSubagentTranscriptArtifactLifecycle>(&mut output, &cfg);
    push_decl::<ClientSubagentTranscriptArtifactStatus>(&mut output, &cfg);
    push_decl::<ClientTask>(&mut output, &cfg);
    push_decl::<ClientTelemetrySummary>(&mut output, &cfg);
    push_decl::<ClientWorktreeLifecycle>(&mut output, &cfg);
    push_decl::<ContextId>(&mut output, &cfg);
    push_decl::<CostEstimate>(&mut output, &cfg);
    push_decl::<EventId>(&mut output, &cfg);
    push_decl::<EventRange>(&mut output, &cfg);
    push_decl::<GuiCommandOutcome>(&mut output, &cfg);
    push_decl::<GuiEvent>(&mut output, &cfg);
    push_decl::<GuiProfile>(&mut output, &cfg);
    push_decl::<GuiRuntimeMode>(&mut output, &cfg);
    push_decl::<GuiShellState>(&mut output, &cfg);
    push_decl::<HandoffEvidenceKind>(&mut output, &cfg);
    push_decl::<HandoffEvidenceRef>(&mut output, &cfg);
    push_decl::<ItemId>(&mut output, &cfg);
    push_decl::<MemoryProposalId>(&mut output, &cfg);
    push_decl::<MutationMode>(&mut output, &cfg);
    push_decl::<MutationRequestId>(&mut output, &cfg);
    push_decl::<MutationRequestOperationKind>(&mut output, &cfg);
    push_decl::<MutationRequestProposal>(&mut output, &cfg);
    push_decl::<MutationRequestStatus>(&mut output, &cfg);
    push_decl::<ApplyPatchDryRunOperationKind>(&mut output, &cfg);
    push_decl::<ApplyPatchDryRunOperationSummary>(&mut output, &cfg);
    push_decl::<ApplyPatchExecutionBlocker>(&mut output, &cfg);
    push_decl::<ApplyPatchExecutionId>(&mut output, &cfg);
    push_decl::<ApplyPatchExecutionRecord>(&mut output, &cfg);
    push_decl::<ApplyPatchExecutionStatus>(&mut output, &cfg);
    push_decl::<ApplyPatchPreflightBlocker>(&mut output, &cfg);
    push_decl::<ApplyPatchPreflightId>(&mut output, &cfg);
    push_decl::<ApplyPatchPreflightRecord>(&mut output, &cfg);
    push_decl::<ApplyPatchPreflightStatus>(&mut output, &cfg);
    push_decl::<PatchApplicationOutcome>(&mut output, &cfg);
    push_decl::<PatchApplicationRecord>(&mut output, &cfg);
    push_decl::<PatchProposal>(&mut output, &cfg);
    push_decl::<PatchProposalId>(&mut output, &cfg);
    push_decl::<RestorePlanId>(&mut output, &cfg);
    push_decl::<RestorePlanRecord>(&mut output, &cfg);
    push_decl::<ReviewBundle>(&mut output, &cfg);
    push_decl::<ReviewBundleId>(&mut output, &cfg);
    push_decl::<ReviewerDecisionKind>(&mut output, &cfg);
    push_decl::<ReviewerGateDecision>(&mut output, &cfg);
    push_decl::<ReviewerGateId>(&mut output, &cfg);
    push_decl::<ReviewerGateRequest>(&mut output, &cfg);
    push_decl::<RuntimeApiAuthMode>(&mut output, &cfg);
    push_decl::<RuntimeApiAuthPolicy>(&mut output, &cfg);
    push_decl::<RuntimeApiBindConfig>(&mut output, &cfg);
    push_decl::<RuntimeApiBindKind>(&mut output, &cfg);
    push_decl::<RuntimeApiCommand>(&mut output, &cfg);
    push_decl::<RuntimeApiCommandAck>(&mut output, &cfg);
    push_decl::<RuntimeApiCommandEnvelope>(&mut output, &cfg);
    push_decl::<RuntimeApiCommandStatus>(&mut output, &cfg);
    push_decl::<RuntimeApiEventStreamRequest>(&mut output, &cfg);
    push_decl::<RuntimeApiQueueOverflow>(&mut output, &cfg);
    push_decl::<RuntimeApiQueuePolicy>(&mut output, &cfg);
    push_decl::<RuntimeApiServerConfig>(&mut output, &cfg);
    push_decl::<RuntimeInstanceId>(&mut output, &cfg);
    push_decl::<SnapshotId>(&mut output, &cfg);
    push_decl::<WorkspaceCheckpointLifecycleRecord>(&mut output, &cfg);
    push_decl::<WorkspaceCheckpointLifecycleStatus>(&mut output, &cfg);
    push_decl::<SubagentApprovalForwarding>(&mut output, &cfg);
    push_decl::<SubagentApprovalForwardingRecord>(&mut output, &cfg);
    push_decl::<SubagentApprovalForwardingStatus>(&mut output, &cfg);
    push_decl::<SubagentCancellationCascade>(&mut output, &cfg);
    push_decl::<SubagentCancellationRecord>(&mut output, &cfg);
    push_decl::<SubagentInactiveParentAction>(&mut output, &cfg);
    push_decl::<SubagentInactivePolicy>(&mut output, &cfg);
    push_decl::<SubagentInactivePolicyRecord>(&mut output, &cfg);
    push_decl::<SubagentRuntimeDecision>(&mut output, &cfg);
    push_decl::<SubagentRuntimeDecisionKind>(&mut output, &cfg);
    push_decl::<SubagentSessionCaps>(&mut output, &cfg);
    push_decl::<SubagentSessionDescriptor>(&mut output, &cfg);
    push_decl::<SubagentSessionId>(&mut output, &cfg);
    push_decl::<SubagentSessionStatus>(&mut output, &cfg);
    push_decl::<SubagentTranscriptArtifactLifecycleRecord>(&mut output, &cfg);
    push_decl::<SubagentTranscriptArtifactRecord>(&mut output, &cfg);
    push_decl::<SubagentTranscriptArtifactStatus>(&mut output, &cfg);
    push_decl::<TaskId>(&mut output, &cfg);
    push_decl::<TaskKind>(&mut output, &cfg);
    push_decl::<TaskOwnerKind>(&mut output, &cfg);
    push_decl::<TaskOwnerStatus>(&mut output, &cfg);
    push_decl::<TaskOwnershipId>(&mut output, &cfg);
    push_decl::<TaskReattachMode>(&mut output, &cfg);
    push_decl::<TaskStatus>(&mut output, &cfg);
    push_decl::<TestPlanId>(&mut output, &cfg);
    push_decl::<TestPlanRecord>(&mut output, &cfg);
    push_decl::<TestRunId>(&mut output, &cfg);
    push_decl::<TestRunRecord>(&mut output, &cfg);
    push_decl::<TestRunStatus>(&mut output, &cfg);
    push_decl::<ThreadId>(&mut output, &cfg);
    push_decl::<Timestamp>(&mut output, &cfg);
    push_decl::<ToolCallId>(&mut output, &cfg);
    push_decl::<ToolId>(&mut output, &cfg);
    output.push_str(TRACE_EVENT_KIND_DECL);
    output.push_str("\n\n");
    push_decl::<TraceRecord>(&mut output, &cfg);
    push_decl::<TurnId>(&mut output, &cfg);
    push_decl::<WorkspaceMutationScope>(&mut output, &cfg);

    output.truncate(output.trim_end_matches('\n').len());
    output.push('\n');

    output
}

pub fn write_bindings(path: impl AsRef<Path>) -> std::io::Result<()> {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, generate_bindings())
}

fn push_decl<T>(output: &mut String, cfg: &Config)
where
    T: TS,
{
    output.push_str(&export_decl(T::decl(cfg)));
    output.push_str("\n\n");
}

fn export_decl(decl: String) -> String {
    decl.strip_prefix("type ")
        .map(|rest| format!("export type {rest}"))
        .unwrap_or(decl)
}
